export const COMPANIES = [
  "Apex Tech Solutions",
  "Global Financial Services",
  "Swift Logistics",
  "Urban Builders",
  "Visionary Marketing Co.",
  "Summit Telecom",
  "Nova Pharmaceuticals",
  "Quantum Software Inc.",
  "Horizon Energy Ltd.",
  "Zenith Auto Parts",
  "SecureNet Security Systems",
  "Stellar Consulting",
  "Orion Fashion House",
  "Vertex Insurance Group",
  "Evergreen Landscaping",
  "Silverline Electronics",
  "Alpine Travel Agency",
  "Velocity Fitness Centers",
  "Pioneer Educational Services",
  "BlueSky Airlines",
  "Titan Heavy Industries",
  "Fusion Digital Media",
  "Elite Home Services",
  "Phoenix Retail Group",
  "Infinity Tech Solutions",
];
