import { Geist, Geist_Mono } from "next/font/google";
import "../../../globals.css";
import UserNavbar from "@/components/UI_Components/USER_Components/USER_Dashboard_Components/UserNabar";
import { getToken } from "@/lib/getToken";
import { redirect } from "next/navigation";
import { SocketProvider } from "@/context/socketContext";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function UserDashboard_Layout({ children }) {
  const token = await getToken();
  if (!token) {
    redirect("/");
  }
  return (
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    <SocketProvider>
      <Toaster />
      <UserNavbar />
      {children}
    </SocketProvider>
    //   </body>
    // </html>
  );
}
